/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 15-Sep-2017 10:06:20 				*/
/*  DBMS       : SQL Server 2008 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Employee_Grade]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Employee] DROP CONSTRAINT [FK_Employee_Grade]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_UserRole_Employee]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [UserRole] DROP CONSTRAINT [FK_UserRole_Employee]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_UserRole_Roles]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [UserRole] DROP CONSTRAINT [FK_UserRole_Roles]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Employee]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Employee]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Grade]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Grade]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Roles]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Roles]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[UserRole]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [UserRole]
GO

/* Create Tables */

CREATE TABLE [Employee]
(
	[employeeId] bigint NOT NULL IDENTITY (1, 1),
	[accountName] varchar(50) NOT NULL,
	[password] varchar(100) NOT NULL,
	[fullName] varchar(100) NOT NULL,
	[gradeId] bigint NOT NULL,
	[stream] varchar(30) NOT NULL,
	[email] varchar(125) NOT NULL,
	[active] bit NOT NULL DEFAULT 1
)
GO

CREATE TABLE [Grade]
(
	[gradeId] bigint NOT NULL IDENTITY (1, 1),
	[jobFamily] varchar(50) NOT NULL,
	[grade] varchar(50) NOT NULL
)
GO

CREATE TABLE [Roles]
(
	[roleId] bigint NOT NULL IDENTITY (1, 1),
	[roleName] varchar(50) NOT NULL
)
GO

CREATE TABLE [UserRole]
(
	[userRoleId] bigint NOT NULL IDENTITY (1, 1),
	[employeeId] bigint NOT NULL,
	[roleId] bigint NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Employee] 
 ADD CONSTRAINT [PK_Employee]
	PRIMARY KEY CLUSTERED ([employeeId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Employee_Grade] 
 ON [Employee] ([gradeId] ASC)
GO

ALTER TABLE [Grade] 
 ADD CONSTRAINT [PK_Grade]
	PRIMARY KEY CLUSTERED ([gradeId] ASC)
GO

ALTER TABLE [Roles] 
 ADD CONSTRAINT [PK_Roles]
	PRIMARY KEY CLUSTERED ([roleId] ASC)
GO

ALTER TABLE [UserRole] 
 ADD CONSTRAINT [PK_UserRole]
	PRIMARY KEY CLUSTERED ([userRoleId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_UserRole_Employee] 
 ON [UserRole] ([employeeId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_UserRole_Roles] 
 ON [UserRole] ([roleId] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Employee] ADD CONSTRAINT [FK_Employee_Grade]
	FOREIGN KEY ([gradeId]) REFERENCES [Grade] ([gradeId]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [UserRole] ADD CONSTRAINT [FK_UserRole_Employee]
	FOREIGN KEY ([employeeId]) REFERENCES [Employee] ([employeeId]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [UserRole] ADD CONSTRAINT [FK_UserRole_Roles]
	FOREIGN KEY ([roleId]) REFERENCES [Roles] ([roleId]) ON DELETE No Action ON UPDATE No Action
GO
